packages:
  - "."

allowBuilds:
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - sharp

overrides:
  fast-uri: ">=3.1.2"
  ajv>fast-uri: "3.1.2"
  protocol-buffers-schema: ">=3.6.1"
  resolve-protobuf-schema>protocol-buffers-schema: "3.6.1"
  minimatch>brace-expansion: "^1.1.14"
